#!/usr/bin/expect -f

# variables
set timeout 30
set pin $env(pin)
set key $env(key)
set qnum $env(qnum)

spawn /opt/cisco/secureclient/bin/vpn connect $env(vpn_server)
expect "YubiKey"
send "1\r"
expect "用户名"
send "$qnum\r"
expect "Password"
send "$key\r"
expect "答"
send "$pin\r"

interact
